[package]
name = "dsc_rsa_pss_4096_sha256_s20_tbs1200"
type = "bin"
authors = ["zk-experiments"]
compiler_version = ">=1.0.0"

[dependencies]
eid_hash = { path = "../../../../../lib/hash" }
eid_rsa = { path = "../../../../../lib/rsa" }
eid_steps = { path = "../../../../../lib/steps" }
csca_registry = { tag = "v0.3.1", git = "https://github.com/zk-experiments/csca-registry", directory = "noir/csca_registry" }
